### ISSUE TITLE
Current state of this project

### ISSUE THREAD

**Issue by mgrossmann** [zowe-plugin-for-gradle/zowe-plugin-for-gradle#2]
Hi,

I would like to get an update on the status of this project. 
Should there be any further development here in the future?
Is this not the case, I would like to take over this.

Many greetings

**Comment by zowe-plugin-for-gradle** [comment]
Hi Mike,

I added you as a collaborator to the repository.

This is something I put together some time ago while I was working on a Java app on z/OS.
Then I kind of forgot about it because I haven't had any free time.
It'd be great if you could turn it into something more useful :)

**Comment by mgrossmann** [comment]
Thanks for the invite
